export const categories = [
  "Corporate Law",
  "Litigation",
  "Real Estate",
  "Employment Law",
  "Intellectual Property",
  "Tax Law",
  "Family Law",
  "Criminal Defense",
]

export const blogPosts = [
  {
    id: 1,
    title: "Understanding Corporate Compliance in 2024",
    excerpt:
      "Navigate the evolving landscape of corporate compliance requirements and best practices for modern businesses.",
    category: "Corporate Law",
    author: "Sarah Johnson",
    date: "2024-01-15",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 2,
    title: "Recent Changes in Employment Law",
    excerpt:
      "Stay informed about the latest updates in employment legislation and their impact on your business operations.",
    category: "Employment Law",
    author: "Michael Chen",
    date: "2024-01-12",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 3,
    title: "Intellectual Property Protection Strategies",
    excerpt: "Learn effective methods to protect your intellectual property assets in an increasingly digital world.",
    category: "Intellectual Property",
    author: "Emily Rodriguez",
    date: "2024-01-10",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 4,
    title: "Real Estate Transaction Best Practices",
    excerpt: "Essential guidelines for smooth real estate transactions and avoiding common legal pitfalls.",
    category: "Real Estate",
    author: "David Thompson",
    date: "2024-01-08",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 5,
    title: "Tax Planning for Small Businesses",
    excerpt: "Strategic tax planning approaches to help small businesses optimize their tax obligations.",
    category: "Tax Law",
    author: "Lisa Wang",
    date: "2024-01-05",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 6,
    title: "Litigation Risk Management",
    excerpt: "Proactive strategies to minimize litigation risks and protect your business interests.",
    category: "Litigation",
    author: "Robert Martinez",
    date: "2024-01-03",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 7,
    title: "Family Law Mediation Benefits",
    excerpt: "Exploring the advantages of mediation in family law disputes and when it might be the right choice.",
    category: "Family Law",
    author: "Jennifer Adams",
    date: "2024-01-01",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 8,
    title: "Criminal Defense Rights Overview",
    excerpt:
      "Understanding your fundamental rights in criminal proceedings and the importance of legal representation.",
    category: "Criminal Defense",
    author: "Thomas Brown",
    date: "2023-12-28",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 9,
    title: "Corporate Merger Legal Considerations",
    excerpt: "Key legal factors to consider when planning corporate mergers and acquisitions.",
    category: "Corporate Law",
    author: "Amanda Foster",
    date: "2023-12-25",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 10,
    title: "Workplace Harassment Prevention",
    excerpt:
      "Implementing effective policies and procedures to prevent workplace harassment and maintain a safe environment.",
    category: "Employment Law",
    author: "Kevin Lee",
    date: "2023-12-22",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 11,
    title: "Patent Application Process Guide",
    excerpt: "Step-by-step guide to navigating the patent application process and protecting your innovations.",
    category: "Intellectual Property",
    author: "Rachel Green",
    date: "2023-12-20",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 12,
    title: "Commercial Lease Negotiations",
    excerpt: "Essential tips for negotiating favorable commercial lease terms and protecting tenant rights.",
    category: "Real Estate",
    author: "Mark Wilson",
    date: "2023-12-18",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 13,
    title: "Estate Tax Planning Strategies",
    excerpt: "Advanced strategies for minimizing estate tax liability and preserving wealth for future generations.",
    category: "Tax Law",
    author: "Susan Davis",
    date: "2023-12-15",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 14,
    title: "Class Action Lawsuit Basics",
    excerpt: "Understanding class action lawsuits, when they apply, and what to expect from the legal process.",
    category: "Litigation",
    author: "James Miller",
    date: "2023-12-12",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
  {
    id: 15,
    title: "Child Custody Legal Framework",
    excerpt: "Comprehensive overview of child custody laws and factors courts consider in custody decisions.",
    category: "Family Law",
    author: "Maria Garcia",
    date: "2023-12-10",
    image: "/placeholder.svg?height=300&width=400",
    content: "Full article content would go here...",
  },
]
